# RHV
RHV_URL = "V2V_INSTANCE_API_URL="
CERT = " V2V_INSTANCE_CA_CERT="
CLUSTER = " V2V_INSTANCE_CLUSTER="

# VMWARE
HOSTNAME = "V2V_INSTANCE_HOSTNAME="

# ALL PROVIDERS
USERNAME = " V2V_INSTANCE_USERNAME="
PASSWORD = " V2V_INSTANCE_PASSWORD="
STORAGE = " STORAGE_CLASS="
NO_HEADLESS = " NO_HEADLESS="
YARN = " yarn run test-suite --specs=\"integration-tests/tests/base.scenario.ts,"
TEST_NAME = " Test"
PARAM_OCP = " --param.openshift"
INST_RHV = "RHV"
INST_VMWARE = "VMWare"
