# RHV
RHV_URL = "V2V_RHV_INSTANCE_API_URL="
RHV_CERT = " V2V_RHV_INSTANCE_CA_CERT="
RHV_CLUSTER = " V2V_RHV_INSTANCE_CLUSTER="
RHV_USERNAME = " V2V_INSTANCE_USERNAME="
RHV_PASSWORD = " V2V_INSTANCE_PASSWORD="

# VMWARE
VMWARE_HOSTNAME = "V2V_VMWARE_INSTANCE_API_URL="
VMWARE_USERNAME = " V2V_VMWARE_INSTANCE_USERNAME="
VMWARE_PASSWORD = " V2V_VMWARE_INSTANCE_PASSWORD="

# ALL PROVIDERS
STORAGE = " STORAGE_CLASS="
VOLUME = " VOLUME_MODE="
NO_HEADLESS = " NO_HEADLESS="
YARN = " yarn run test-protractor-suite --specs=\"integration-tests/tests/base.scenario.ts,"
TEST_NAME = " Test"
PARAM_OCP = " --param.openshift"
INST_RHV = "RHV"
INST_VMWARE = "VMWare"
